mdapipkg/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Odoo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Odoo ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

mdapipkg/unpackaged/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount_due__c</fullName>
        <description>Comes From Odoo</description>
        <label>Amount due</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer_Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_ref__c</fullName>
        <description>Comes From Odoo</description>
        <label>Customer ref</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_date__c</fullName>
        <description>Comes From Odoo</description>
        <label>End date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Odoo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Odoo ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_state__c</fullName>
        <description>Comes From Odoo</description>
        <label>Payment state</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_date__c</fullName>
        <description>Comes From Odoo</description>
        <label>Start date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <description>Comes From Odoo</description>
        <label>Tax</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax_excluded__c</fullName>
        <description>Comes From Odoo</description>
        <label>Tax excluded</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <description>Comes From Odoo</description>
        <label>Total</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <description>Comes From Odoo</description>
        <label>Discount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>List_price__c</fullName>
        <description>Comes From Odoo</description>
        <label>List price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Odoo_Id__c</fullName>
        <externalId>true</externalId>
        <label>Odoo Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Comes From Odoo</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Comes From Odoo</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_price__c</fullName>
        <description>Comes From Odoo</description>
        <label>Total price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <label>Invoice Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Odoo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Odoo ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
</CustomObject>

Prod V2/main/default/classes/OdooInvoiceService.cls
/**
 * @Version: 1.0
 * @Author: Upeo
 * @Copyright: 2021 Upeo Consulting
 * @Uses:
 *
 * -----------------------------------------------------------------------------------------------
 * Description: 
 *
 *
 * Created: 18/09/2023
 * Last Updated: 18/09/2023
 *
 * Unit tests:
 *
 * Change log:
 * -----------------------------------------------------------------------------------------------
*/
/**
@Description:

@Change Log:

@Dependencies:

@Test Classes:

*/

public class OdooInvoiceService {

    public static void parseAccountMoveToInvoice(List<OdooAccountMove.Data> odooInvoices){


        List<Invoice__c> invoices = new List<Invoice__c>();
        List<Invoice_Line__c> invoiceLines = new List<Invoice_Line__c>();

        Schema.SObjectField invId = Invoice__c.Fields.Odoo_Id__c;
        Schema.SObjectField invLineId = Invoice_Line__c.Fields.Odoo_Id__c;

        for(OdooAccountMove.Data odooInvoice : odooInvoices){
            if(Date.valueOf(odooInvoice.attributes.start_date).year() >= Date.today().year()-1) {
                invoices.add(mapAccountMoveToInvoice(odooInvoice));
                if (odooInvoice.attributes.invoice_lines != null) {
                    invoiceLines.addAll(mapAccountMoveLineToInvoiceLine(odooInvoice.attributes.invoice_lines));
                }
            }
        }

        System.debug('invoices: ' + invoices.size());
        System.debug('invoiceLines: ' + invoiceLines.size());

        List<Database.UpsertResult> invoiceUpserts = DMLHandler.upsertRecordsWithReturn(invId, invoices);
        List<Database.UpsertResult> invoiceLineUpserts = DMLHandler.upsertRecordsWithReturn(invLineId, invoiceLines);

        Integer successCount = 0;
        Integer errorCount = 0;

        for(Database.UpsertResult invoiceUpsert : invoiceUpserts){
            if(invoiceUpsert.isSuccess()){
                //System.debug('Invoice upsert success: ' + invoiceUpsert.getId());
                successCount++;
            }else{
                //System.debug('Invoice upsert error: ' + invoiceUpsert.getErrors());
                errorCount++;
            }
        }

        System.debug('Invoice upsert success count: ' + successCount);
        System.debug('Invoice upsert error count: ' + errorCount);

        successCount = 0;
        errorCount = 0;

        for(Database.UpsertResult lineUpsert : invoiceLineUpserts){
            if(lineUpsert.isSuccess()){
                //System.debug('Invoice line upsert success: ' + lineUpsert.getId());
                successCount++;
            }else{
                //System.debug('Invoice line upsert error: ' + lineUpsert.getErrors());
                errorCount++;
            }
        }

        System.debug('Invoice line upsert success count: ' + successCount);
        System.debug('Invoice line upsert error count: ' + errorCount);

    }

    public static Invoice__c mapAccountMoveToInvoice(OdooAccountMove.Data odooInvoice){

        //System.debug('odooInvoice: ' + odooInvoice.attributes.account_name);

        Invoice__c invoice = new Invoice__c();
        invoice.Customer_Account_Name__r = new Account(Odoo_ID__c = odooInvoice.attributes.account_name);
        invoice.Name = odooInvoice.attributes.name;
        invoice.Customer_ref__c = odooInvoice.attributes.customer_ref;
        invoice.Odoo_ID__c = odooInvoice.Id;
        invoice.Payment_state__c = odooInvoice.attributes.payment_state != null ? odooInvoice.attributes.payment_state.replace('_', ' ') : 'unknown';
        invoice.Tax__c = odooInvoice.attributes.tax;
        invoice.Total__c = odooInvoice.attributes.total;
        invoice.Tax_excluded__c = odooInvoice.attributes.tax_excluded;
        invoice.Start_date__c = odooInvoice.attributes.start_date != null ? Date.valueOf(odooInvoice.attributes.start_date) : null;
        invoice.End_date__c = odooInvoice.attributes.end_date != null ? Date.valueOf(odooInvoice.attributes.end_date) : null;
        invoice.Amount_due__c = odooInvoice.attributes.amount_due;
        return invoice;
    }

    public Static List<Invoice_Line__c> mapAccountMoveLineToInvoiceLine(List<OdooAccountMove.InvoiceLines> odooInvoiceLines){
        List<Invoice_Line__c> invoiceLines = new List<Invoice_Line__c>();
        for(OdooAccountMove.InvoiceLines odooInvoiceLine : odooInvoiceLines){
            Invoice_Line__c invoiceLine = new Invoice_Line__c();
            invoiceLine.Invoice__r = new Invoice__c(Odoo_ID__c = odooInvoiceLine.attributes.account_move_id);
            invoiceLine.Odoo_ID__c = odooInvoiceLine.Id;
            invoiceLine.Product__r = new Product2(Odoo_ID__c = odooInvoiceLine.attributes.product_id);
            invoiceLine.Quantity__c = odooInvoiceLine.attributes.quantity;
            invoiceLine.List_price__c = odooInvoiceLine.attributes.list_price;
            invoiceLine.Total_price__c = odooInvoiceLine.attributes.total_price;
            invoiceLine.Discount__c = odooInvoiceLine.attributes.discount;
            invoiceLine.Name = odooInvoiceLine.attributes.description;
            invoiceLines.add(invoiceLine);
        }
        return invoiceLines;
    }

}