mdapipkg/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Labels__c</fullName>
        <description>Which Brands are sold - comes from the &apos;Labels&apos; field in Odoo</description>
        <inlineHelpText>Which Brands are sold?</inlineHelpText>
        <label>Labels</label>
        <length>250</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapipkg/unpackaged/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Labels__c</fullName>
        <label>Labels</label>
        <length>250</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapipkg/unpackaged/objects/Odoo_Config__c.object
<CustomObject>
    <fields>
        <fullName>Table__c</fullName>
        <label>Table</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Odoo Config</label>
    <nameField>
        <displayFormat>OC-{00000}</displayFormat>
        <label>Odoo Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Odoo Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod V2/main/default/classes/SearchableComboboxController.cls
/**
 * @Version: 1.0
 * @Author: Upeo
 * @Copyright: 2021 Upeo Consulting
 * @Uses:
 *
 * -----------------------------------------------------------------------------------------------
 * Description: 
 *
 *
 * Created: 20/10/2023
 * Last Updated: 20/10/2023
 *
 * Unit tests:
 *
 * Change log:
 * -----------------------------------------------------------------------------------------------
*/
/**
@Description:

@Change Log:

@Dependencies:

@Test Classes:

*/

public with sharing class SearchableComboboxController {

    @AuraEnabled
    public static List<String> getObjectValues() {
        List<String> objectValues = new List<String>();
        List<Odoo_Config__c> odooConfigs = [SELECT Id, Name, Text_Value__c FROM Odoo_Config__c Where Table__c = 'Labels'];
        for(Odoo_Config__c odooConfig : odooConfigs) {
            objectValues.add(odooConfig.Text_Value__c);
        }
        System.debug('objectValues: ' + objectValues);
        return objectValues;
    }

    @AuraEnabled
    public static String getAccountLabels(String recordId){
        return [SELECT Id, Labels__c FROM Account Where Id = :recordId].Labels__c;
    }

    @AuraEnabled
    public static String getLeadLabels(String recordId){
        return [SELECT Id, Labels__c FROM Lead Where Id = :recordId].Labels__c;
    }

}