mdapipkg/unpackaged/objects/Odoo_Config__c.object
<CustomObject>
    <fields>
        <fullName>Identifier__c</fullName>
        <label>Identifier</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Table__c</fullName>
        <label>Table</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Odoo Config</label>
    <nameField>
        <displayFormat>OC-{00000}</displayFormat>
        <label>Odoo Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Odoo Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Prod V2/main/default/classes/OdooConfigHelper.cls
/**
 * @Version: 1.0
 * @Author: Upeo
 * @Copyright: 2021 Upeo Consulting
 * @Uses:
 *
 * -----------------------------------------------------------------------------------------------
 * Description: 
 *
 *
 * Created: 20/10/2023
 * Last Updated: 20/10/2023
 *
 * Unit tests:
 *
 * Change log:
 * -----------------------------------------------------------------------------------------------
*/
/**
@Description:

@Change Log:

@Dependencies:

@Test Classes:

*/

public with sharing class OdooConfigHelper {

    public static String getTextFromIdentifier(Integer identifier, String tableName) {
        String text = '';

        try {
            text = [SELECT Name FROM Odoo_Config__c WHERE Identifier__c = :identifier AND Table__c =: tableName LIMIT 1].Text_Value__c;
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
        }
        return text;
    }

    public static Integer getIdentifierFromText(String textValue, String tableName){

        Integer identifier;

        try {
            identifier = Integer.valueOf([SELECT Identifier__c FROM Odoo_Config__c WHERE Text_Value__c = :textValue AND Table__c =: tableName LIMIT 1].Identifier__c);
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
        }
        return identifier;
    }

}