mdapipkg/unpackaged/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>from which package was this added to the opportunity</description>
        <label>Package</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapipkg/unpackaged/objects/Package__c.object
<CustomObject>
    <description>Object to group products in yearly and starters packages</description>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Package_Line__c.object
<CustomObject>
    <description>object to link a package to the products and the correct price</description>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Package__c</fullName>
        <description>To which package is this Line linked?</description>
        <label>Package</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Package Lines</relationshipLabel>
        <relationshipName>Package_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>From Which Price book does this Package Line come from</description>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Package Lines</relationshipLabel>
        <relationshipName>Package_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Which price is this line (based on product and pricelist)</description>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Which product is linked to this package line?</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Package Lines</relationshipLabel>
        <relationshipName>Package_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>comes from Odoo Integration</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Package Line</label>
    <nameField>
        <displayFormat>PL{0000000000}</displayFormat>
        <label>Package Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Prod V2/main/default/classes/CreateStarterPackageLines.cls
/**
 * Created by fpardon on 25/09/2023.
 */

public without sharing class CreateStarterPackageLines {

    public class RequestWrapper {
        @InvocableVariable(Required=true Label='Opportunity' Description='The Opportunity for which to create the Starter Package Lines')
        public Opportunity opportunity;
        @InvocableVariable(Required=true Label='Package' Description='The Starter Package to create the Starter Package Lines from')
        public Package__c starterPackage;
    }


    @InvocableMethod(Label='Create Package Lines from Starter Package' Description='Create Package Lines from Starter Package')
    public static void createOLILines(List<RequestWrapper> requestWrappers) {
        for (RequestWrapper requestWrapper : requestWrappers) {
            createStarterPackageLines(requestWrapper.opportunity, requestWrapper.starterPackage);
        }
    }

    public static void createStarterPackageLines(Opportunity opp, Package__c starterPackage){

        System.debug('opp ' + opp);
        System.debug('starterPackage ' + starterPackage);

        Opportunity oppWithPricebook = [SELECT Id, Pricebook2Id FROM Opportunity WHERE Id = :opp.Id];


        List<PricebookEntry> pricebookEntries = [SELECT Id, Product2Id, UnitPrice from PricebookEntry WHERE Pricebook2Id = :oppWithPricebook.Pricebook2Id];
        List<Package_Line__c> packageLines = [SELECT Id, Product__c, Price__c,Quantity__c from Package_Line__c WHERE Package__c = :starterPackage.Id AND External_Id__c != null AND Price_Book__c = :oppWithPricebook.Pricebook2Id];

        System.debug('pbEntries size ' + pricebookEntries.size());
        System.debug('packageLines size ' + packageLines.size());

        Map<String, String> productMap = new Map<String, String>();
        Map<String, Decimal> priceMap = new Map<String, Decimal>();
        for(PricebookEntry pbe : pricebookEntries){
            productMap.put(pbe.Product2Id, pbe.Id);
            priceMap.put(pbe.Product2Id, pbe.UnitPrice);
        }

        List<OpportunityLineItem> oppLineItems = new List<OpportunityLineItem>();

        for(Package_Line__c pLine : packageLines){
            if(productMap.containsKey(pLine.Product__c)){
                System.debug('contains key');
                System.debug('pLine ' + pLine);
                System.debug('productMap.get(pLine.Product__c) ' + productMap.get(pLine.Product__c));
                System.debug('priceMap.get(pLine.Product__c) ' + priceMap.get(pLine.Product__c));
                OpportunityLineItem oli = new OpportunityLineItem();
                oli.OpportunityId = opp.Id;
                oli.PricebookEntryId = productMap.get(pLine.Product__c);
                oli.Quantity = pLine.Quantity__c;
                oli.UnitPrice = priceMap.get(pLine.Product__c) != null ? priceMap.get(pLine.Product__c) : 0;
                oppLineItems.add(oli);
            } else {
                System.debug('does not contain key');
            }
        }
        
        System.debug('after loop, size of oppLineItems ' + oppLineItems.size());
        insert oppLineItems;
    }



}