mdapipkg/unpackaged/objects/Package__c.object
<CustomObject>
    <description>Object to group products in yearly and starters packages</description>
    <fields>
        <fullName>Allowed_Pricelist_Ids__c</fullName>
        <label>Allowed Pricelist Ids</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Odoo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Odoo ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Package_Line__c.object
<CustomObject>
    <description>object to link a package to the products and the correct price</description>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Odoo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Odoo ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Package__c</fullName>
        <description>To which package is this Line linked?</description>
        <label>Package</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Package Lines</relationshipLabel>
        <relationshipName>Package_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>From Which Price book does this Package Line come from</description>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Package Lines</relationshipLabel>
        <relationshipName>Package_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Which price is this line (based on product and pricelist)</description>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Which product is linked to this package line?</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Package Lines</relationshipLabel>
        <relationshipName>Package_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>comes from Odoo Integration</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Package Line</label>
    <nameField>
        <displayFormat>PL{0000000000}</displayFormat>
        <label>Package Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Package_Price_Book__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Package__c</fullName>
        <label>Package</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Package - Price Books</relationshipLabel>
        <relationshipName>Package_Price_Books</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Package - Price Books</relationshipLabel>
        <relationshipName>Package_Price_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Package - Price Book</label>
    <nameField>
        <displayFormat>PPB-{00000000}</displayFormat>
        <label>Package - Price Book Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package - Price Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Odoo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Odoo ID</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

mdapipkg/unpackaged/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Odoo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Odoo ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapipkg/unpackaged/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Odoo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Odoo ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
</CustomObject>

Prod V2/main/default/classes/PackageLineHandlerBatch.cls
/**
 * @Version: 1.0
 * @Author: Upeo
 * @Copyright: 2021 Upeo Consulting
 * @Uses:
 *
 * -----------------------------------------------------------------------------------------------
 * Description: 
 *
 *
 * Created: 15/09/2023
 * Last Updated: 15/09/2023
 *
 * Unit tests:
 *
 * Change log:
 * -----------------------------------------------------------------------------------------------
*/
/**
@Description:

@Change Log:

@Dependencies:

@Test Classes:

*/

global class PackageLineHandlerBatch implements Database.Batchable<sObject>{

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'select id, Product__r.Id, Package__r.Allowed_PriceList_Ids__c, Product__c, Package__c, Quantity__c, Odoo_ID__c FROM Package_Line__c WHERE Odoo_ID__c != null AND Product__r.Odoo_Id__c != null AND Package__c != null';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Package_Line__c> scope) {

        System.debug('scope: ' + scope.size());

        List<Package_Line__c> packageLines = new List<Package_Line__c>();
        List<String> productIds = new List<String>();
        for(Package_Line__c packageLine : scope){
            if(packageLine.Product__c != null && productIds.contains(packageLine.Product__c) == false){
                productIds.add(packageLine.Product__c);
            }
        }

        System.debug('productIds: ' + productIds.size());

        List<PricebookEntry> pricebookEntries = [SELECT Id, Product2Id, Pricebook2Id, Pricebook2.Odoo_ID__c, UnitPrice FROM PricebookEntry WHERE Product2Id IN :productIds AND Pricebook2.Odoo_ID__c != null];

        System.debug('pricebookEntries: ' + pricebookEntries.size());

        for(Package_Line__c pLine : scope){
            for(PricebookEntry pbe : pricebookEntries){
                System.debug('pLine.Product__r.Id: ' + pLine.Product__r.Id);
                System.debug('pbe.Product2Id: ' + pbe.Product2Id);
                if(pLine.Product__r.Id == pbe.Product2Id){
                    System.debug('pLine.Package__r.Allowed_PriceList_Ids__c: ' + pLine.Package__r.Allowed_PriceList_Ids__c);
                    if(pLine.Package__r.Allowed_PriceList_Ids__c == null || pLine.Package__r.Allowed_PriceList_Ids__c.contains(String.valueOf(pbe.Pricebook2.Odoo_ID__c))) {
                        Package_Line__c newPackageLine = new Package_Line__c();
                        newPackageLine.Product__c = pLine.Product__c;
                        newPackageLine.Package__c = pLine.Package__c;
                        newPackageLine.Quantity__c = pLine.Quantity__c;
                        newPackageLine.Price__c = pbe.UnitPrice;
                        newPackageLine.External_Id__c = pLine.Odoo_ID__c + '-' + pbe.Id;
                        newPackageLine.Price_Book__c = pbe.Pricebook2Id;
                        packageLines.add(newPackageLine);
                    }
                }
            }
        }

        System.debug('packageLines: ' + packageLines.size());
        upsert packageLines External_Id__c;

    }

    global void finish(Database.BatchableContext BC) {

        List<Package_Price_Book__c> pPBooks = new List<Package_Price_Book__c>();

        List<Package__c> packs = [SELECT Id, Allowed_Pricelist_Ids__c, Odoo_Id__c from Package__c];

        for(Package__c pack : packs){
            if(pack.Allowed_Pricelist_Ids__c != null){
                List<String> plists = pack.Allowed_Pricelist_Ids__c.split(';');
                for(String pb : plists){
                    System.debug('pb ' +pb);
                    Package_Price_Book__c ppb = new Package_Price_Book__c();
                    ppb.Package__c = pack.Id;
                    ppb.Price_Book__r = new Pricebook2(Odoo_Id__c = Integer.valueOf(pb));
                    ppb.External_Id__c = pack.Odoo_Id__c + '-' + pb;
                    System.debug(ppb);
                    pPBooks.add(ppb);
                }
            }
        }

        upsert pPBooks External_Id__c;

    }



}